### Get Comment
GET http://localhost:8080/api/product/1/comment
Content-Type: application/json


### Create Comment(including Image file)
POST http://localhost:8080/api/comment/1
Content-Type: multipart/form-data; boundary=abcd

--abcd
Content-Disposition: form-data; name="comment"
Content-Type: application/json

{
"title": "제목1",
"comment": "코멘트1",
"username": "닉네임1"
}
--abcd
Content-Disposition: form-data; name="imageUrl"; filename="2.JPG"
Content-Type: multipart/form-data

< ./2.JPG

### Create Comment(only comment)
POST http://localhost:8080/api/comment/1
Content-Type: multipart/form-data; boundary=abcd

--abcd
Content-Disposition: form-data; name="comment"
Content-Type: application/json

{
"title": "제목2",
"comment": "코멘트2",
"username": "닉네임1"
}
--abcd
Content-Disposition: form-data; name="imageUrl"; filename=""
Content-Type: multipart/form-data


### Update Comment(including Image file)
PUT http://localhost:8080/api/comment/1
Content-Type: multipart/form-data; boundary=abcd

--abcd
Content-Disposition: form-data; name="comment"
Content-Type: application/json

{
"title": "제목수정1",
"comment": "코멘트수정1",
"username": "닉네임1"
}
--abcd
Content-Disposition: form-data; name="imageUrl"; filename="3.JPG"
Content-Type: multipart/form-data

< ./3.JPG


### Update Comment(only comment)
PUT http://localhost:8080/api/comment/2
Content-Type: multipart/form-data; boundary=abcd

--abcd
Content-Disposition: form-data; name="comment"
Content-Type: application/json

{
"title": "제목수정1212",
"comment": "코멘트수정1212",
"username": "닉네임1"
}
--abcd
Content-Disposition: form-data; name="imageUrl"; filename=""
Content-Type: multipart/form-data


### Delete Comment
DELETE http://localhost:8080/api/comment/2
Content-Type: application/json